### PR TITLE
Adds rule to prevent backfill in data migration

### PR DESCRIPTION
**Pull request by atareshawty**
This rule naively checks that no methods defined in [ActiveRecord::Persistence](https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html) are called inside a class that inherits from `ActiveRecord::Migration`

### CODE REVIEW

**Comment by TAGraves** [comment]
Oh, also - are we preventing raw SQL execution via `execute`? If not, we probably should prevent that.

**Comment by atareshawty** [comment]
> Oh, also - are we preventing raw SQL execution via execute? If not, we probably should prevent that.

We'd have to be careful to avoid breaking `collapsed_migrations` migrations since they execute the `prod` schema files. I can see how we would do that. Alternatively, we could just add an inline comment to each of those migrations but I'm not sure if I'd want to make that a practice.

> Did you consider making a whitelist rather than a blacklist? We could consider only allowing the methods defined in ...

I think that would end up making this rule more complicated to reason about. For example, consider this migration I found in root-server:

```ruby
class CreateClaimFeatureEstimates < ActiveRecord::Migration[5.1]
  def change
    create_table :claim_feature_estimates, :id => :uuid do |t|
      t.references :claim_feature, :type => :uuid, :foreign_key => true, :null => false
      t.integer :total_value_in_cents
      t.string :method_of_inspection, :index => true, :null => false
      t.timestamps
    end
  end
end
```

The methods `references`, `integer`, `string`, and `timestamps` are outside of our supposed whitelist, but are still valid. The only way I see to get around that is to check whether a method call is inside a method in our whitelist. If we did that however, we'd need to make sure something like `User.all.each { |u| u.update! }` wasn't happening which might require a separate whitelist. The different combinations of use cases this rule would support might become unruly. 


Ultimately, we can't enforce every possible case where a database migration can go wrong. Imo if people are going crazy things in migrations like executing hand-rolled sql, that is a process problem and needs to be stopped at code review time.

**Comment by TAGraves** [comment]
@atareshawty That definitely makes sense re: the whitelist approach. I'm still in favor of forbidding execute, only because I've seen new engineers here do it a few different times. Those were all caught in peer review, but I think that case is common enough to prevent it (with a work-around for collapsed migrations).

**Comment by atareshawty** [comment]
@TAGraves check out https://github.com/Root-App/root-ruby-style/pull/5/commits/c1227b4e681be661264fff74f60c4e8f0bcc82f5. Is that what you had in mind?

**Comment by TAGraves** [comment]
Yep - looks good to me!

**Pull request merged**
